const ACCOUNT_INFO = 'ACCOUNT_INFO';
const CASH_WITHDRAWAL = 'CASH_WITHDRAWAL';
const CHARGE = 'CHARGE';
const DEPOSIT = 'DEPOSIT';
const FAST_TRANSFER = 'FAST_TRANSFER';
const IDENTIFICATION_BY_PHONE = 'IDENTIFICATION_BY_PHONE';
const LIMIT_MODIFICATION = 'LIMIT_MODIFICATION';
const NIP_CHANGE = 'NIP_CHANGE';
const PHONE_RECHARGE = 'PHONE_RECHARGE';
const SPEI_INCOME = 'SPEI_INCOME';
const DIGITAL_DEBIT_CARD_CANCELLED = 'DIGITAL_DEBIT_CARD_CANCELLED';
const DIGITAL_DEBIT_CARD_ACTIVATED = 'DIGITAL_DEBIT_CARD_ACTIVATED';
const DIGITAL_DEBIT_CARD_BLOCKED = 'DIGITAL_DEBIT_CARD_BLOCKED';
const DEBIT_CARD_BLOCKED = 'DEBIT_CARD_BLOCKED';

module.exports = {
  ACCOUNT_INFO,
  CASH_WITHDRAWAL,
  CHARGE,
  DEPOSIT,
  FAST_TRANSFER,
  IDENTIFICATION_BY_PHONE,
  LIMIT_MODIFICATION,
  NIP_CHANGE,
  PHONE_RECHARGE,
  SPEI_INCOME,
  DIGITAL_DEBIT_CARD_CANCELLED,
  DIGITAL_DEBIT_CARD_ACTIVATED,
  DIGITAL_DEBIT_CARD_BLOCKED,
  DEBIT_CARD_BLOCKED
};
