const ACCOUNT_INFO = 'ACCOUNT_INFO';
const CASH_WITHDRAWAL = 'CASH_WITHDRAWAL';
const CHARGE = 'CHARGE';
const DEPOSIT = 'DEPOSIT';
const FAST_TRANSFER = 'FAST_TRANSFER';
const IDENTIFICATION_BY_PHONE = 'IDENTIFICATION_BY_PHONE';
const LIMIT_MODIFICATION = 'LIMIT_MODIFICATION';
const NIP_CHANGE = 'NIP_CHANGE';
const PHONE_RECHARGE = 'PHONE_RECHARGE';
const SPEI_INCOME = 'SPEI_INCOME';

module.exports = {
  ACCOUNT_INFO,
  CASH_WITHDRAWAL,
  CHARGE,
  DEPOSIT,
  FAST_TRANSFER,
  IDENTIFICATION_BY_PHONE,
  LIMIT_MODIFICATION,
  NIP_CHANGE,
  PHONE_RECHARGE,
  SPEI_INCOME
};
